version: '3.1'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-pass
    ports:
      - 27017:27017
    volumes:
      - /usr/local/mongodb/data:/data/db
    secrets:
      - mongo-root-pass
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo-root-pass
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #     ME_CONFIG_MONGODB_PORT: 27017
  #   depends_on:
  #     mongo:
  #       condition: service_healthy
  #   secrets:
  #     - mongo-root-pass
  gluetun:
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      VPN_SERVICE_PROVIDER: nordvpn
      OPENVPN_USER_SECRETFILE: /run/secrets/nord-user
      OPENVPN_PASSWORD_SECRETFILE: /run/secrets/nord-pass
      SERVER_REGIONS: "United States"
      HTTPPROXY: on
      HTTPPROXY_LOG: on
    ports:
      - 8888:8888/tcp
    secrets:
      - nord-user
      - nord-pass

  web:
    build: 
      context: ../
      dockerfile: ./docker/docker/web/Dockerfile
    restart: unless-stopped
    environment:
      MONGO_SERVER: mongo
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASS_FILE: /run/secrets/mongo-root-pass
      MONGO_DB_NAME: stock-notify
      SCRAPER_ENABLED: "true"
      SCRAPER_PROXY: "http://gluetun:8888"
    ports:
      - "5500:8080"
    depends_on:
      mongo:
        condition: service_healthy
      gluetun:
        condition: service_healthy
    secrets:
      - mongo-root-pass
    cap_add:
      - SYS_ADMIN


secrets:
  mongo-root-pass:
    file: ./config/mongo-root-pass.txt
  nord-user:
    file: ./config/nord-user.txt
  nord-pass:
    file: ./config/nord-pass.txt