version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-pass
    secrets:
      - mongo-root-pass
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo-root-pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      mongo:
        condition: service_healthy
    secrets:
      - mongo-root-pass
  web:
    build: 
      context: ../
      dockerfile: ./docker/docker/web/Dockerfile
    environment:
      MONGO_SERVER: mongo
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASS_FILE: /run/secrets/mongo-root-pass
      MONGO_DB_NAME: stock-notify
      SCRAPER_ENABLED: "true"
    ports:
      - "5500:8080"
    depends_on:
      mongo:
        condition: service_healthy
    secrets:
      - mongo-root-pass
    cap_add:
      - SYS_ADMIN
secrets:
  mongo-root-pass:
    file: ./config/mongo-root-pass.txt